<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [2]:
import numpy as np
def generate():
    a1 = np.zeros(8)
    a1[2] = a1[-1] = 2
    return a1 
new_arr = generate()
print(new_arr)

[0. 0. 2. 0. 0. 0. 0. 2.]


### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [6]:
import numpy as np
def generate():
    a2= np.arange(1,10)
    return a2
ret_arr= generate()
print(ret_arr)

[1 2 3 4 5 6 7 8 9]


### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [21]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
        for i in range(series.size):
            series[i] = series[i].capitalize()
        return series 
new_series = generate() 
print(new_series)

0              How
1               To
2            Learn
3    Data science?
dtype: object


### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [85]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
mean_list = []
def generate():
    for row in matrix_fab:
        arr_np = np.array(row)
        print(np.mean(arr_np))
        mean_list.append(np.mean(arr_np))
    matrix_mean = np.array(mean_list).reshape(1,3)
    matrix_sub = matrix_fab - matrix_mean
    print(matrix_sub)
    max_matrix = []
    for row in matrix_sub:
        local_arr = np.array(row)
        max_ele = np.max(local_arr)
        max_matrix.append(max_ele)
    max_div_matrix = np.array(max_matrix).reshape(1,3)
    final_matrix = matrix_sub / max_div_matrix
    print(final_matrix)
    return final_matrix
final_res = generate()
print(final_res)

1.0
4.0
7.0
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]
[[ 1.  -1.5 -1. ]
 [-2.   0.  -0.4]
 [-5.   1.5  0.2]]
[[ 1.  -1.5 -1. ]
 [-2.   0.  -0.4]
 [-5.   1.5  0.2]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [32]:
import numpy as np
def generate():
    arr = np.random.rand(12)
    print(arr,"\n")
    sorted_array = np.sort(arr)[::-1].reshape(4,3)
    print(sorted_array,"\n")
    return sorted_array
new_arr = generate()
print(new_arr)

[0.19251867 0.35890188 0.45474238 0.24854326 0.66058306 0.9326723
 0.90283533 0.72627196 0.89780511 0.92776226 0.03385139 0.10338422] 

[[0.9326723  0.92776226 0.90283533]
 [0.89780511 0.72627196 0.66058306]
 [0.45474238 0.35890188 0.24854326]
 [0.19251867 0.10338422 0.03385139]] 

[[0.9326723  0.92776226 0.90283533]
 [0.89780511 0.72627196 0.66058306]
 [0.45474238 0.35890188 0.24854326]
 [0.19251867 0.10338422 0.03385139]]


### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [74]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df1 = pd.DataFrame(data)
    df2 = pd.DataFrame(labels,columns=['Label'])
    df3 = pd.concat([df1,df2],axis=1)
    df3.set_index('Label',inplace=True)
    print(df3)
    print(df3[df3['age'] is pd.notna])
    
  
   
    # Write your code here
    return # your variable
generate()

      animal  age  visits priority
Label                             
a        cat  2.5       1      yes
b        cat  3.0       3      yes
c      snake  0.5       2       no
d        dog  NaN       3      yes
e        dog  5.0       2       no
f        cat  2.0       3       no
g      snake  4.5       1       no
h        cat  NaN       1      yes
i        dog  7.0       2       no
j        dog  3.0       1       no


KeyError: False

## 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [5]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
def generate():
    # write your code here
    # Also print df
    return # your variable i.e mean_age
generate()

### 8.  From the given dataframe get the positions where values of two columns match?

In [10]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    # your code here
    return None
generate()

### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [7]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    # your code here
    # print(series)
    return # your variable
generate()

### 10. Stack two given series vertically and horizontally ? Print out both.

In [8]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    # your code 
    # print out both vertically and horizontally stacked series.
    return None
generate()