In [1]:
import numpy as np

In [8]:
np.random.rand(5,2)

array([[0.59259137, 0.37974829],
       [0.74089365, 0.19656649],
       [0.31308082, 0.92383127],
       [0.80012451, 0.20272633],
       [0.78661859, 0.00927382]])

In [10]:
np.random.rand(2,3)

array([[0.94244956, 0.09846727, 0.6845413 ],
       [0.87637006, 0.82734091, 0.490964  ]])

In [12]:
np.random.randn(5,4)

array([[-1.75627984, -0.71974418, -0.2856745 , -0.08351908],
       [ 0.49372561,  0.49782807,  0.72857228, -0.28315651],
       [ 0.941906  ,  0.23789677, -0.19121907, -1.68746575],
       [ 0.36991867, -0.01431991,  1.20267418, -1.84508268],
       [-1.19974824,  1.28443555,  0.10406974,  0.11798041]])

In [14]:
sixteen_rand_val = np.random.randn(16)
print(sixteen_rand_val)

[-0.24149219 -0.74450549  1.19040635  0.59245844 -0.33930083  0.21000426
  1.14497104  0.01968352 -0.79780854 -0.04475003 -1.77804053 -0.40789283
 -0.60728168 -1.10953161 -0.99191902  0.83631334]


In [19]:
new_array = sixteen_rand_val.reshape(4,4)
print(new_array)

[[-0.24149219 -0.74450549  1.19040635  0.59245844]
 [-0.33930083  0.21000426  1.14497104  0.01968352]
 [-0.79780854 -0.04475003 -1.77804053 -0.40789283]
 [-0.60728168 -1.10953161 -0.99191902  0.83631334]]


In [25]:
a1 = np.random.randn(20).reshape(4,5)
a1

array([[-2.22165844, -1.5252492 , -0.08968278, -1.13626962,  2.43268823],
       [-0.26085123,  1.45983582,  0.01616508, -1.06620938,  1.03560426],
       [-2.3742998 ,  0.51879722, -0.45119776,  0.76851056, -0.1869182 ],
       [ 0.0930116 ,  0.13735217, -0.45592634, -1.67782643,  0.49241921]])

In [26]:
print(a1.shape)

(4, 5)


In [27]:
print(a1.ndim)

2


In [35]:
a1 = np.arange(12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
a1[1:3,1:]

array([[4, 5],
       [7, 8]])

In [38]:
a1[0::3,1:]

array([[ 1,  2],
       [10, 11]])

In [40]:
a1>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
a1[a1>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
a1 = np.array([[10,11,12,13]])
a1.shape

(1, 4)

In [48]:
arr = np.array([2,2,3,4,2,6,7,8,2,10,11])

In [51]:
np.where(arr == arr.min())

(array([0, 1, 4, 8], dtype=int64),)

In [52]:
np.where(arr == arr.min())[0]

array([0, 1, 4, 8], dtype=int64)

In [55]:
np.where(arr == arr.min())[0][-1]

8

In [56]:
arr2 = np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
arr2.mean()

4.5

In [58]:
arr2.mean(axis=1)

array([2., 7.])

In [59]:
arr2.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [61]:
arr2.min(axis=1)

array([0, 5])

In [63]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
arr1= np.arange(10,20).reshape(2,5)
arr1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
arr3= np.concatenate((arr1,arr2))
arr3

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [74]:
arr4= np.concatenate((arr1,arr2),axis=1)
arr4

array([[10, 11, 12, 13, 14,  0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19,  5,  6,  7,  8,  9]])

In [75]:
np.hsplit(arr4,2)

[array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]), array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])]

In [76]:
np.vsplit(arr4,2)

[array([[10, 11, 12, 13, 14,  0,  1,  2,  3,  4]]),
 array([[15, 16, 17, 18, 19,  5,  6,  7,  8,  9]])]